site_name: "@sematext/logagent"
repo_url: https://github.com/sematext/logagent-js
theme: readthedocs
pages:
- Features and Overview: index.md
- Installation: installation.md
- Windows Installation: windows.md
- Usage: cli-parameters.md
- Configuration file: config-file.md
- Log Parser and pattern definitions: parser.md
- Plugins: 
  - Overview: plugins.md
  - Output plugins: 
    - Elasticsearch: output-elasticsearch.md
- Filter: 
  - About filters: filters.md
  - Grep input filter: input-filter-grep.md
  - SQL output filter: output-filter-sql.md

